#!/usr/bin/env python3
"""Enrich KPL programme metadata with Tencent Video detail-page fields."""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
import uuid
from collections import deque
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor, wait
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


PAGE_SERVICE_URL = (
    "https://pbaccess.video.qq.com/trpc.vector_layout.page_view.PageService/getPage"
    "?video_appid=3000010&vversion_platform=2&vversion_name=8.5.96"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read fetch_kpl_programmes.py JSON output and add Tencent Video "
            "play count, description, aspect ratio, tags, and like count."
        )
    )
    parser.add_argument(
        "--input",
        default="data/kpl_programmes.json",
        help="Input JSON generated by fetch_kpl_programmes.py.",
    )
    parser.add_argument(
        "--output",
        default="data/kpl_programmes_enriched.json",
        help="Output enriched JSON path.",
    )
    parser.add_argument(
        "--csv-output",
        default="data/kpl_programmes_enriched.csv",
        help="Output enriched CSV path.",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Delay after each Tencent Video request inside a worker. Default: 0.",
    )
    parser.add_argument(
        "--max-workers",
        type=int,
        default=0,
        help="Maximum parallel detail requests. Default: adaptive cap based on CPU and total videos.",
    )
    parser.add_argument(
        "--min-workers",
        type=int,
        default=2,
        help="Minimum adaptive parallelism after rate limiting. Default: 2",
    )
    parser.add_argument(
        "--checkpoint-every",
        type=int,
        default=100,
        help="Write a resumable checkpoint after this many completed videos. Default: 100",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=3,
        help="Retries per video. Default: 3",
    )
    parser.add_argument(
        "--max-videos",
        type=int,
        default=None,
        help="Limit videos for testing. Default: process every video.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Reuse existing output and only fetch videos without enrichment fields.",
    )
    return parser.parse_args()


def post_page_service(vid: str, retries: int) -> dict[str, Any]:
    device_guid = uuid.uuid4().hex
    url = f"{PAGE_SERVICE_URL}&vdevice_guid={device_guid}"
    payload = {
        "page_params": {
            "ad_wechat_authorization_status": "0",
            "req_from": "web_vsite",
            "ad_exp_ids": "",
            "pc_sdk_version": "",
            "pc_oaid": "",
            "new_mark_label_enabled": "1",
            "pc_device_info": "",
            "support_pc_yyb_mobile_app_engine": "0",
            "pc_wegame_version": "",
            "cid": "",
            "vid": vid,
        },
        "page_bypass_params": {
            "params": {"caller_id": "3000010", "platform_id": "2"},
            "scene": "desk_detail",
            "app_version": "",
            "abtest_bypass_id": device_guid,
        },
        "page_context": {},
    }
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    request = Request(
        url,
        data=body,
        headers={
            "Accept": "application/json, text/plain, */*",
            "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
            "Content-Type": "application/json",
            "Origin": "https://v.qq.com",
            "Referer": f"https://v.qq.com/x/page/{vid}.html",
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"
            ),
        },
        method="POST",
    )

    last_error: Exception | None = None
    for attempt in range(1, retries + 1):
        try:
            with urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8"))
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
            last_error = exc
            if attempt < retries:
                time.sleep(min(2 * attempt, 8))
    raise RuntimeError(f"PageService failed for {vid} after {retries} retries: {last_error}")


def iter_param_blocks(node: Any) -> list[dict[str, Any]]:
    blocks: list[dict[str, Any]] = []

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            params = value.get("params")
            if isinstance(params, dict) and params:
                blocks.append(params)
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    walk(node)
    return blocks


def parse_count_from_text(text: str) -> int | None:
    match = re.search(r"([\d,.]+)\s*次播放", text or "")
    if not match:
        return None
    return int(match.group(1).replace(",", "").replace(".", ""))


def normalize_tags(value: Any) -> list[str]:
    if not value:
        return []
    if isinstance(value, list):
        items = value
    elif isinstance(value, str):
        try:
            parsed = json.loads(value)
            items = parsed if isinstance(parsed, list) else []
        except json.JSONDecodeError:
            return [part.strip() for part in re.split(r"[,，/|]", value) if part.strip()]
    else:
        return []

    tags: list[str] = []
    for item in items:
        if isinstance(item, str) and item.strip():
            tags.append(item.strip())
        elif isinstance(item, dict):
            for key in ("tag_name", "name", "title", "text"):
                text = item.get(key)
                if isinstance(text, str) and text.strip():
                    tags.append(text.strip())
                    break
    return tags


def to_int(value: Any) -> int | None:
    if value in (None, ""):
        return None
    try:
        return int(float(str(value).replace(",", "")))
    except ValueError:
        return None


def to_float(value: Any) -> float | None:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def extract_detail_fields(response: dict[str, Any]) -> dict[str, Any]:
    if response.get("ret") != 0:
        raise RuntimeError(f"PageService ret={response.get('ret')}: {response.get('msg')}")

    blocks = iter_param_blocks(response.get("data") or {})
    intro = next((block for block in blocks if block.get("detail_info")), {})
    video = next((block for block in blocks if block.get("vid") and ("video_like_num" in block)), {})

    detail_info = str(intro.get("detail_info") or intro.get("normal_matrix_info") or "")
    fields = {
        "play_count": parse_count_from_text(detail_info),
        "video_description": intro.get("video_description") or video.get("desc") or "",
        "aspect_ratio": to_float(intro.get("video_aspect") or video.get("aspect")),
        "tag_list": normalize_tags(intro.get("tag_list")),
        "like_count": to_int(video.get("video_like_num") or video.get("format_video_like_num")),
        "tencent_detail_info": detail_info,
        "tencent_detail_fetched_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    return fields


def enrich_video(video: dict[str, Any], retries: int) -> dict[str, Any]:
    vid = str(video.get("vfid") or video.get("vid") or "")
    if not vid:
        return {**video, "tencent_detail_error": "missing vid/vfid"}

    try:
        detail = extract_detail_fields(post_page_service(vid, retries))
        return {**video, **detail}
    except Exception as exc:  # Keep the batch moving and preserve which item failed.
        return {
            **video,
            "tencent_detail_error": str(exc),
            "tencent_detail_fetched_at_utc": datetime.now(timezone.utc).isoformat(),
        }


def fetch_and_enrich_video(video: dict[str, Any], retries: int, sleep: float) -> dict[str, Any]:
    vid = str(video.get("vfid") or video.get("vid") or "")
    if not vid:
        return {**video, "tencent_detail_error": "missing vid/vfid"}
    detail = extract_detail_fields(post_page_service(vid, retries))
    if sleep > 0:
        time.sleep(sleep)
    return {**video, **detail}


def load_payload(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def video_key(video: dict[str, Any]) -> str:
    return str(video.get("vfid") or video.get("vid") or "")


def has_detail(video: dict[str, Any]) -> bool:
    return "play_count" in video and "like_count" in video and "tencent_detail_fetched_at_utc" in video


def load_resume(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        return {}
    payload = load_payload(path)
    videos = payload.get("videos") or []
    if not isinstance(videos, list):
        return {}
    return {
        video_key(item): item
        for item in videos
        if isinstance(item, dict) and video_key(item) and has_detail(item)
    }


def checkpoint_path(output_path: Path) -> Path:
    return output_path.with_name(f"{output_path.stem}.checkpoint{output_path.suffix}")


def default_max_workers(total: int) -> int:
    cpu = os.cpu_count() or 4
    return max(1, min(32, max(8, cpu * 4), total))


def is_rate_limit_error(exc: BaseException) -> bool:
    text = str(exc).lower()
    markers = [
        "429",
        "403",
        "502",
        "503",
        "504",
        "too many",
        "rate",
        "limit",
        "timeout",
        "timed out",
        "temporarily",
        "connection reset",
    ]
    return any(marker in text for marker in markers)


def write_checkpoint(path: Path, payload: dict[str, Any], videos: list[dict[str, Any]], metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(
        json.dumps({**payload, "metadata": metadata, "videos": videos}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    tmp_path.replace(path)


def write_csv(path: Path, videos: list[dict[str, Any]]) -> None:
    preferred_fields = [
        "vfid",
        "title",
        "play_count",
        "create_timestamp",
        "create_time_utc",
        "video_description",
        "aspect_ratio",
        "tag_list",
        "duration",
        "cover_url",
        "like_count",
        "tencent_detail_info",
        "seasonid",
        "tag_id",
        "play_url",
        "source_page",
        "source_index",
        "tencent_detail_error",
    ]
    extra_fields = sorted({key for video in videos for key in video if key not in preferred_fields})
    fields = preferred_fields + extra_fields

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for video in videos:
            row = dict(video)
            if isinstance(row.get("tag_list"), list):
                row["tag_list"] = "|".join(row["tag_list"])
            writer.writerow(row)


def enrich_all(args: argparse.Namespace) -> tuple[dict[str, Any], list[dict[str, Any]], dict[str, Any]]:
    input_path = Path(args.input)
    output_path = Path(args.output)
    payload = load_payload(input_path)
    videos = payload.get("videos")
    if not isinstance(videos, list):
        raise RuntimeError("input JSON must contain a videos list")

    limit = args.max_videos or len(videos)
    results: list[dict[str, Any] | None] = [None] * len(videos)
    pending: deque[tuple[int, dict[str, Any], int]] = deque()
    resume_items: dict[str, dict[str, Any]] = {}
    if args.resume:
        resume_items.update(load_resume(output_path))
        resume_items.update(load_resume(checkpoint_path(output_path)))

    reused_count = 0
    skipped_count = 0
    for index, video in enumerate(videos):
        key = video_key(video)
        if index >= limit:
            results[index] = dict(video)
            skipped_count += 1
        elif args.resume and key and key in resume_items:
            results[index] = resume_items[key]
            reused_count += 1
        else:
            pending.append((index, video, 0))

    max_workers = args.max_workers or default_max_workers(len(pending))
    max_workers = max(1, min(max_workers, max(1, len(pending) or 1)))
    min_workers = max(1, min(args.min_workers, max_workers))
    target_workers = max_workers
    completed_count = reused_count + skipped_count
    fetched_count = 0
    retry_count = 0
    error_count = 0
    rate_limit_count = 0
    success_streak = 0
    next_submit_at = 0.0

    metadata = dict(payload.get("metadata") or {})
    metadata.update(
        {
            "tencent_detail_enriched_at_utc": datetime.now(timezone.utc).isoformat(),
            "tencent_detail_source": PAGE_SERVICE_URL,
            "tencent_detail_requested_videos": limit,
            "tencent_detail_reused_count": reused_count,
            "tencent_detail_skipped_count": skipped_count,
            "tencent_detail_fetched_count": 0,
            "tencent_detail_error_count": 0,
            "tencent_detail_retry_count": 0,
            "rate_limit_count": 0,
            "adaptive_max_workers": max_workers,
            "adaptive_min_workers": min_workers,
            "adaptive_final_workers": target_workers,
        }
    )

    if not pending:
        return payload, [item if item is not None else {} for item in results], metadata

    print(
        f"adaptive video detail fetch: total={len(videos)}, requested={limit}, "
        f"pending={len(pending)}, workers={target_workers}/{max_workers}",
        flush=True,
    )

    in_flight: dict[Future[dict[str, Any]], tuple[int, dict[str, Any], int]] = {}
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        while pending or in_flight:
            now = time.monotonic()
            while pending and len(in_flight) < target_workers and now >= next_submit_at:
                task = pending.popleft()
                _, video, _ = task
                future = executor.submit(fetch_and_enrich_video, video, args.retries, args.sleep)
                in_flight[future] = task
                now = time.monotonic()

            if not in_flight:
                time.sleep(max(0.05, next_submit_at - time.monotonic()))
                continue

            done, _ = wait(in_flight, timeout=0.25, return_when=FIRST_COMPLETED)
            if not done:
                continue

            for future in done:
                index, video, attempts = in_flight.pop(future)
                key = video_key(video)
                try:
                    results[index] = future.result()
                except Exception as exc:
                    if is_rate_limit_error(exc) and attempts < args.retries + 3:
                        rate_limit_count += 1
                        retry_count += 1
                        pending.appendleft((index, video, attempts + 1))
                        old_target = target_workers
                        target_workers = max(min_workers, max(1, target_workers // 2))
                        success_streak = 0
                        next_submit_at = time.monotonic() + min(30.0, 2.0 * (attempts + 1))
                        print(
                            f"rate limit/backoff: workers {old_target}->{target_workers}, "
                            f"retry {key} ({exc})",
                            flush=True,
                        )
                        continue
                    if attempts < args.retries:
                        retry_count += 1
                        pending.append((index, video, attempts + 1))
                        continue
                    error_count += 1
                    results[index] = {
                        **video,
                        "tencent_detail_error": str(exc),
                        "tencent_detail_fetched_at_utc": datetime.now(timezone.utc).isoformat(),
                    }

                fetched_count += 1
                completed_count += 1
                success_streak += 1

                if target_workers < max_workers and success_streak >= max(10, target_workers * 3):
                    old_target = target_workers
                    target_workers += 1
                    success_streak = 0
                    print(f"adaptive recovery: workers {old_target}->{target_workers}", flush=True)

                if completed_count == 1 or completed_count % 50 == 0 or completed_count == len(videos):
                    print(
                        f"video detail {completed_count}/{len(videos)}: "
                        f"workers={target_workers}/{max_workers}, fetched={fetched_count}, "
                        f"reused={reused_count}, errors={error_count}, retries={retry_count}",
                        flush=True,
                    )

                if args.checkpoint_every > 0 and completed_count % args.checkpoint_every == 0:
                    partial = [item for item in results if item is not None]
                    checkpoint_metadata = {
                        **metadata,
                        "checkpointed_at_utc": datetime.now(timezone.utc).isoformat(),
                        "tencent_detail_processed_videos": len(partial),
                        "tencent_detail_fetched_count": fetched_count,
                        "tencent_detail_reused_count": reused_count,
                        "tencent_detail_error_count": error_count,
                        "tencent_detail_retry_count": retry_count,
                        "rate_limit_count": rate_limit_count,
                        "adaptive_final_workers": target_workers,
                    }
                    write_checkpoint(checkpoint_path(output_path), payload, partial, checkpoint_metadata)

    enriched = [item if item is not None else {} for item in results]
    metadata.update(
        {
            "tencent_detail_enriched_at_utc": datetime.now(timezone.utc).isoformat(),
            "tencent_detail_processed_videos": len(enriched),
            "tencent_detail_fetched_count": fetched_count,
            "tencent_detail_reused_count": reused_count,
            "tencent_detail_error_count": error_count,
            "tencent_detail_retry_count": retry_count,
            "rate_limit_count": rate_limit_count,
            "adaptive_final_workers": target_workers,
        }
    )
    return payload, enriched, metadata


def write_outputs(payload: dict[str, Any], videos: list[dict[str, Any]], metadata: dict[str, Any], json_path: Path, csv_path: Path) -> None:
    output_payload = {**payload, "metadata": metadata, "videos": videos}
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(output_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    write_csv(csv_path, videos)
    print(f"saved: {json_path}")
    print(f"saved: {csv_path}")


def main() -> int:
    args = parse_args()
    if args.sleep < 0:
        print("--sleep must not be negative", file=sys.stderr)
        return 2
    if args.retries <= 0:
        print("--retries must be positive", file=sys.stderr)
        return 2
    if args.max_workers < 0:
        print("--max-workers must not be negative", file=sys.stderr)
        return 2
    if args.min_workers <= 0:
        print("--min-workers must be positive", file=sys.stderr)
        return 2
    if args.checkpoint_every < 0:
        print("--checkpoint-every must not be negative", file=sys.stderr)
        return 2
    if args.max_videos is not None and args.max_videos <= 0:
        print("--max-videos must be positive", file=sys.stderr)
        return 2

    try:
        payload, videos, metadata = enrich_all(args)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    write_outputs(payload, videos, metadata, Path(args.output), Path(args.csv_output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
