#!/usr/bin/env python3
"""Add official KPL schedule detail records and playback links."""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
from collections import deque
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor, wait
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote

from fetch_kpl_schedules import DETAIL_API, post_json, require_success


PLAYBACK_URL_PREFIX = "https://kpl.qq.com/#/PlayBack"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read data/kpl_schedules.json, fetch getScheduleDetail for each match, "
            "and add per-round playback links."
        )
    )
    parser.add_argument(
        "--input",
        default="data/kpl_schedules.json",
        help="Input JSON generated by fetch_kpl_schedules.py.",
    )
    parser.add_argument(
        "--output",
        default="data/kpl_schedules_enriched.json",
        help="Output enriched JSON path.",
    )
    parser.add_argument(
        "--csv-output",
        default="data/kpl_schedules_enriched.csv",
        help="Output enriched CSV path.",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.0,
        help="Delay after each detail request inside a worker. Default: 0.",
    )
    parser.add_argument(
        "--max-workers",
        type=int,
        default=0,
        help=(
            "Maximum parallel detail requests. Default: adaptive cap based on CPU "
            "and total matches."
        ),
    )
    parser.add_argument(
        "--min-workers",
        type=int,
        default=2,
        help="Minimum adaptive parallelism after rate limiting. Default: 2",
    )
    parser.add_argument(
        "--checkpoint-every",
        type=int,
        default=100,
        help="Write a resumable checkpoint after this many completed matches. Default: 100",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=3,
        help="Retries per detail request. Default: 3",
    )
    parser.add_argument(
        "--max-matches",
        type=int,
        default=None,
        help="Limit matches for testing. Default: process every match.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Reuse existing output and only fetch matches missing detail fields.",
    )
    return parser.parse_args()


def playback_url(seasonid: str, scheduleid: str, round_number: Any) -> str:
    return (
        f"{PLAYBACK_URL_PREFIX}?seasonid={quote(seasonid or '')}"
        f"&scheduleid={quote(scheduleid or '')}"
        f"&round={quote(str(round_number or ''))}"
    )


def fetch_schedule_detail(seasonid: str, scheduleid: str, retries: int) -> dict[str, Any]:
    payload = {"seasonid": seasonid, "scheduleid": scheduleid}
    return require_success(
        post_json(DETAIL_API, payload, retries),
        f"getScheduleDetail({seasonid}, {scheduleid})",
    )


def add_playback_links(schedule: dict[str, Any], detail: dict[str, Any]) -> dict[str, Any]:
    seasonid = str(schedule.get("seasonid") or "")
    scheduleid = str(schedule.get("scheduleid") or "")
    round_details = detail.get("round_details") or []
    linked_rounds: list[dict[str, Any]] = []

    for round_item in round_details:
        if not isinstance(round_item, dict):
            continue
        linked = dict(round_item)
        linked["playback_url"] = playback_url(seasonid, scheduleid, linked.get("round"))
        linked_rounds.append(linked)

    enriched = dict(schedule)
    enriched["detail"] = {**detail, "round_details": linked_rounds}
    enriched["round_details"] = linked_rounds
    enriched["round_count"] = len(linked_rounds)
    enriched["round_vids"] = ",".join(
        str(round_item.get("vid") or "") for round_item in linked_rounds if round_item.get("vid")
    )
    enriched["round_playback_urls"] = ",".join(
        round_item["playback_url"] for round_item in linked_rounds if round_item.get("playback_url")
    )
    enriched["match_playback_url"] = playback_url(seasonid, scheduleid, "")
    return enriched


def load_input(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    schedules = payload.get("schedules") or []
    metadata = payload.get("metadata") or {}
    if not isinstance(schedules, list):
        raise RuntimeError(f"{path} does not contain a schedules list")
    if not isinstance(metadata, dict):
        metadata = {}
    return schedules, metadata


def load_resume(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    schedules = payload.get("schedules") or []
    if not isinstance(schedules, list):
        return {}
    return {
        str(item.get("scheduleid")): item
        for item in schedules
        if isinstance(item, dict) and item.get("scheduleid") and item.get("detail")
    }


def checkpoint_path(output_path: Path) -> Path:
    return output_path.with_name(f"{output_path.stem}.checkpoint{output_path.suffix}")


def default_max_workers(total: int) -> int:
    cpu = os.cpu_count() or 4
    return max(1, min(32, max(8, cpu * 4), total))


def is_rate_limit_error(exc: BaseException) -> bool:
    text = str(exc).lower()
    markers = [
        "429",
        "403",
        "502",
        "503",
        "504",
        "too many",
        "rate",
        "limit",
        "timeout",
        "timed out",
        "temporarily",
        "connection reset",
    ]
    return any(marker in text for marker in markers)


def write_checkpoint(path: Path, schedules: list[dict[str, Any]], metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(
        json.dumps({"metadata": metadata, "schedules": schedules}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    tmp_path.replace(path)


def fetch_and_enrich(schedule: dict[str, Any], retries: int, sleep: float) -> dict[str, Any]:
    seasonid = str(schedule.get("seasonid") or "")
    scheduleid = str(schedule.get("scheduleid") or "")
    detail = fetch_schedule_detail(seasonid, scheduleid, retries)
    if sleep > 0:
        time.sleep(sleep)
    return add_playback_links(schedule, detail)


def enrich_all(args: argparse.Namespace) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    input_path = Path(args.input)
    output_path = Path(args.output)
    schedules, source_metadata = load_input(input_path)
    if args.max_matches is not None:
        schedules = schedules[: args.max_matches]

    resume_items: dict[str, dict[str, Any]] = {}
    if args.resume:
        resume_items.update(load_resume(output_path))
        resume_items.update(load_resume(checkpoint_path(output_path)))

    results: list[dict[str, Any] | None] = [None] * len(schedules)
    pending: deque[tuple[int, dict[str, Any], int]] = deque()
    reused_count = 0
    skipped_count = 0

    for index, schedule in enumerate(schedules):
        scheduleid = str(schedule.get("scheduleid") or "")
        seasonid = str(schedule.get("seasonid") or "")
        if not scheduleid or not seasonid:
            results[index] = dict(schedule)
            skipped_count += 1
        elif scheduleid in resume_items:
            results[index] = resume_items[scheduleid]
            reused_count += 1
        else:
            pending.append((index, schedule, 0))

    max_workers = args.max_workers or default_max_workers(len(pending))
    max_workers = max(1, min(max_workers, max(1, len(pending) or 1)))
    min_workers = max(1, min(args.min_workers, max_workers))
    target_workers = max_workers
    completed_count = reused_count + skipped_count
    fetched_count = 0
    retry_count = 0
    rate_limit_count = 0
    success_streak = 0
    next_submit_at = 0.0

    metadata = {
        "source_input": str(input_path),
        "source_metadata": source_metadata,
        "detail_api_url": DETAIL_API,
        "playback_url_prefix": PLAYBACK_URL_PREFIX,
        "fetched_at_utc": datetime.now(timezone.utc).isoformat(),
        "processed_match_count": len(schedules),
        "detail_fetched_count": 0,
        "detail_reused_count": reused_count,
        "detail_skipped_count": skipped_count,
        "detail_retry_count": 0,
        "rate_limit_count": 0,
        "adaptive_max_workers": max_workers,
        "adaptive_min_workers": min_workers,
        "adaptive_final_workers": target_workers,
    }

    if not pending:
        return [item if item is not None else {} for item in results], metadata

    print(
        f"adaptive detail fetch: total={len(schedules)}, "
        f"pending={len(pending)}, workers={target_workers}/{max_workers}",
        flush=True,
    )

    in_flight: dict[Future[dict[str, Any]], tuple[int, dict[str, Any], int]] = {}
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        while pending or in_flight:
            now = time.monotonic()
            while pending and len(in_flight) < target_workers and now >= next_submit_at:
                task = pending.popleft()
                _, schedule, _ = task
                future = executor.submit(fetch_and_enrich, schedule, args.retries, args.sleep)
                in_flight[future] = task
                now = time.monotonic()

            if not in_flight:
                sleep_for = max(0.05, next_submit_at - time.monotonic())
                time.sleep(sleep_for)
                continue

            done, _ = wait(in_flight, timeout=0.25, return_when=FIRST_COMPLETED)
            if not done:
                continue

            for future in done:
                index, schedule, attempts = in_flight.pop(future)
                scheduleid = str(schedule.get("scheduleid") or "")
                seasonid = str(schedule.get("seasonid") or "")
                try:
                    results[index] = future.result()
                except Exception as exc:
                    if is_rate_limit_error(exc) and attempts < args.retries + 3:
                        rate_limit_count += 1
                        retry_count += 1
                        pending.appendleft((index, schedule, attempts + 1))
                        old_target = target_workers
                        target_workers = max(min_workers, max(1, target_workers // 2))
                        success_streak = 0
                        next_submit_at = time.monotonic() + min(30.0, 2.0 * (attempts + 1))
                        print(
                            f"rate limit/backoff: workers {old_target}->{target_workers}, "
                            f"retry {seasonid} {scheduleid} ({exc})",
                            flush=True,
                        )
                        continue
                    if attempts < args.retries:
                        retry_count += 1
                        pending.append((index, schedule, attempts + 1))
                        continue
                    raise RuntimeError(f"detail failed for {seasonid} {scheduleid}: {exc}") from exc

                fetched_count += 1
                completed_count += 1
                success_streak += 1

                if target_workers < max_workers and success_streak >= max(10, target_workers * 3):
                    old_target = target_workers
                    target_workers += 1
                    success_streak = 0
                    print(f"adaptive recovery: workers {old_target}->{target_workers}", flush=True)

                if (
                    completed_count == 1
                    or completed_count % 50 == 0
                    or completed_count == len(schedules)
                ):
                    print(
                        f"detail {completed_count}/{len(schedules)}: "
                        f"workers={target_workers}/{max_workers}, fetched={fetched_count}, "
                        f"reused={reused_count}, retries={retry_count}",
                        flush=True,
                    )

                if args.checkpoint_every > 0 and completed_count % args.checkpoint_every == 0:
                    partial = [item for item in results if item is not None]
                    checkpoint_metadata = {
                        **metadata,
                        "checkpointed_at_utc": datetime.now(timezone.utc).isoformat(),
                        "processed_match_count": len(partial),
                        "detail_fetched_count": fetched_count,
                        "detail_reused_count": reused_count,
                        "detail_retry_count": retry_count,
                        "rate_limit_count": rate_limit_count,
                        "adaptive_final_workers": target_workers,
                    }
                    write_checkpoint(checkpoint_path(output_path), partial, checkpoint_metadata)

    enriched_schedules = [item if item is not None else {} for item in results]
    metadata.update(
        {
            "fetched_at_utc": datetime.now(timezone.utc).isoformat(),
            "processed_match_count": len(enriched_schedules),
            "detail_fetched_count": fetched_count,
            "detail_reused_count": reused_count,
            "detail_retry_count": retry_count,
            "rate_limit_count": rate_limit_count,
            "adaptive_final_workers": target_workers,
        }
    )
    return enriched_schedules, metadata


def csv_value(value: Any) -> Any:
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    return value


def write_outputs(
    json_path: Path,
    csv_path: Path,
    schedules: list[dict[str, Any]],
    metadata: dict[str, Any],
) -> None:
    json_path.parent.mkdir(parents=True, exist_ok=True)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"metadata": metadata, "schedules": schedules}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    preferred_fields = [
        "scheduleid",
        "seasonid",
        "season_name",
        "season_year",
        "stageid",
        "stage_name",
        "competition_format",
        "start_timestamp",
        "start_time_utc",
        "schedule_status",
        "schedule_status_text",
        "team_a_name",
        "team_a_score",
        "team_b_name",
        "team_b_score",
        "bo_total",
        "round_count",
        "round_vids",
        "match_playback_url",
        "round_playback_urls",
        "location_name",
        "round_details",
        "detail",
    ]
    extra_fields = sorted({key for item in schedules for key in item if key not in preferred_fields})
    fields = preferred_fields + extra_fields

    with csv_path.open("w", newline="", encoding="utf-8-sig") as file:
        writer = csv.DictWriter(file, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for item in schedules:
            writer.writerow({field: csv_value(item.get(field, "")) for field in fields})

    print(f"saved: {json_path}")
    print(f"saved: {csv_path}")


def main() -> int:
    args = parse_args()
    if args.sleep < 0:
        print("--sleep must not be negative", file=sys.stderr)
        return 2
    if args.retries <= 0:
        print("--retries must be positive", file=sys.stderr)
        return 2
    if args.max_workers < 0:
        print("--max-workers must not be negative", file=sys.stderr)
        return 2
    if args.min_workers <= 0:
        print("--min-workers must be positive", file=sys.stderr)
        return 2
    if args.checkpoint_every < 0:
        print("--checkpoint-every must not be negative", file=sys.stderr)
        return 2
    if args.max_matches is not None and args.max_matches <= 0:
        print("--max-matches must be positive", file=sys.stderr)
        return 2

    schedules, metadata = enrich_all(args)
    write_outputs(Path(args.output), Path(args.csv_output), schedules, metadata)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
